version: '2'
services:

  api:
    image: weseek/stackstorm:1.5
    env_file: ./common.env
    environment:
      - "ST2_SERVICE=st2api"
    labels:
      - "com.stackstorm.service.provides=api"
    depends_on:
      - "mongodb"
      - "rabbitmq"
      - "redis"
      - "auth"
    expose:
      - "9101"
    volumes:
      - /opt/stackstorm/packs/sodb:/opt/stackstorm/packs/sodb

  action:
    image: weseek/stackstorm:1.5
    env_file: ./common.env
    environment:
      - "ST2_SERVICE=st2actionrunner"
    labels:
      - "com.stackstorm.service.provides=actionrunner"
    depends_on:
      - "mongodb"
      - "rabbitmq"
      - "api"
    volumes:
      - /opt/stackstorm/packs/sodb:/opt/stackstorm/packs/sodb

  auth:
    image: weseek/stackstorm:1.5
    env_file: ./common.env
    environment:
      - "ST2_SERVICE=st2auth"
    labels:
      - "com.stackstorm.service.provides=auth"
    depends_on:
      - "mongodb"
      - "rabbitmq"
    expose:
      - "9100"
    ports:
      - "9100:9100"
    volumes:
      - /opt/stackstorm/packs/sodb:/opt/stackstorm/packs/sodb

  notifier:
    image: weseek/stackstorm:1.5
    env_file: ./common.env
    environment:
      - "ST2_SERVICE=st2notifier"
    labels:
      - "com.stackstorm.service.provides=notifier"
    depends_on:
      - "mongodb"
      - "rabbitmq"
      - "redis"
      - "api"
    volumes:
      - /opt/stackstorm/packs/sodb:/opt/stackstorm/packs/sodb

  results:
    image: weseek/stackstorm:1.5
    env_file: ./common.env
    environment:
      - "ST2_SERVICE=st2resultstracker"
    labels:
      - "com.stackstorm.service.provides=resultstracker"
    depends_on:
      - "mongodb"
      - "rabbitmq"
      - "api"
    volumes:
      - /opt/stackstorm/packs/sodb:/opt/stackstorm/packs/sodb

  rules:
    image: weseek/stackstorm:1.5
    env_file: ./common.env
    environment:
      - "ST2_SERVICE=st2rulesengine"
    labels:
      - "com.stackstorm.service.provides=rulesengine"
    depends_on:
      - "mongodb"
      - "rabbitmq"
      - "api"
    volumes:
      - /opt/stackstorm/packs/sodb:/opt/stackstorm/packs/sodb

  sensor:
    image: weseek/stackstorm:1.5
    env_file: ./common.env
    environment:
      - "ST2_SERVICE=st2sensorcontainer"
    labels:
      - "com.stackstorm.service.provides=sensorcontainer"
    depends_on:
      - "mongodb"
      - "rabbitmq"
      - "api"
    volumes:
      - /opt/stackstorm/packs/sodb:/opt/stackstorm/packs/sodb

  gc:
    image: weseek/stackstorm:1.5
    env_file: ./common.env
    environment:
      - "ST2_SERVICE=st2garbagecollector"
    labels:
      - "com.stackstorm.service.provides=garbagecollector"
    depends_on:
      - "mongodb"
      - "rabbitmq"
      - "api"
    volumes:
      - /opt/stackstorm/packs/sodb:/opt/stackstorm/packs/sodb

  exporter:
    image: weseek/stackstorm:1.5
    env_file: ./common.env
    environment:
      - "ST2_SERVICE=st2exporter"
    labels:
      - "com.stackstorm.service.provides=exporter"
    depends_on:
      - "mongodb"
      - "rabbitmq"
      - "api"
    volumes:
      - /opt/stackstorm/packs/sodb:/opt/stackstorm/packs/sodb

  stream:
    image: weseek/stackstorm:1.5
    env_file: ./common.env
    environment:
      - "ST2_SERVICE=st2stream"
    labels:
      - "com.stackstorm.service.provides=stream"
    depends_on:
      - "mongodb"
      - "rabbitmq"
    volumes:
      - /opt/stackstorm/packs/sodb:/opt/stackstorm/packs/sodb
    expose:
      - "9102"

  web:
    image: weseek/stackstorm:1.5
    environment:
      - "ST2_SERVICE=st2web"
      - "ST2_API_URL=http://api:9101"
      - "ST2_AUTH_URL=http://auth:9100"
    ports:
      - "8080:80"
      - "9101:9101"
    depends_on:
      - "api"
      - "stream"

  register:
    image: weseek/stackstorm:1.5
    env_file: ./common.env
    environment:
      - "ST2_SERVICE=st2-register-content"
    command: "--register-all"
    depends_on:
      - "mongodb"
      - "rabbitmq"
    volumes:
      - /opt/stackstorm/packs/sodb:/opt/stackstorm/packs/sodb

  rabbitmq:
    image: rabbitmq:management
    environment:
      - "RABBITMQ_DEFAULT_USER=rmq-user"
      - "RABBITMQ_DEFAULT_PASS=rmq-pass"
    hostname: rabbitmq
    expose:
      - "5672"

  mongodb:
    image: tutum/mongodb
    environment:
      - "MONGODB_USER=stackstorm-user"
      - "MONGODB_PASS=stackstorm-pass"
      - "MONGODB_DATABASE=stackstorm-db"
    expose:
      - "27017"

  redis:
    image: redis:3.0-alpine
    expose:
      - "6379"
