version: '2'
services:

  api:
    image: weseek/stackstorm:1.5
    env_file: ./common.env
    environment:
      - "ST2_SERVICE=st2api"
    labels:
      - "com.stackstorm.service.provides=api"
    depends_on:
      - "mongodb"
      - "rabbitmq"
      - "auth"
    expose:
      - "9101"
    ports:
     - "9101:9101"

  action:
    image: weseek/stackstorm:1.5
    env_file: ./common.env
    environment:
      - "ST2_SERVICE=st2actionrunner"
    labels:
      - "com.stackstorm.service.provides=actionrunner"
    depends_on:
      - "mongodb"
      - "rabbitmq"
      - "api"

  auth:
    image: weseek/stackstorm:1.5
    env_file: ./common.env
    environment:
      - "ST2_SERVICE=st2auth"
    labels:
      - "com.stackstorm.service.provides=auth"
    depends_on:
      - "mongodb"
      - "rabbitmq"
    expose:
      - "9100"
    ports:
      - "9100:9100"

  notifier:
    image: weseek/stackstorm:1.5
    env_file: ./common.env
    environment:
      - "ST2_SERVICE=st2notifier"
    labels:
      - "com.stackstorm.service.provides=notifier"
    depends_on:
      - "mongodb"
      - "rabbitmq"
      - "api"

  results:
    image: weseek/stackstorm:1.5
    env_file: ./common.env
    environment:
      - "ST2_SERVICE=st2resultstracker"
    labels:
      - "com.stackstorm.service.provides=resultstracker"
    depends_on:
      - "mongodb"
      - "rabbitmq"
      - "api"

  rules:
    image: weseek/stackstorm:1.5
    env_file: ./common.env
    environment:
      - "ST2_SERVICE=st2rulesengine"
    labels:
      - "com.stackstorm.service.provides=rulesengine"
    depends_on:
      - "mongodb"
      - "rabbitmq"
      - "api"

  web:
    image: weseek/stackstorm:1.5
    environment:
      - "ST2_SERVICE=st2web"
      - "ST2_API_URL=http://api:9101"
      - "ST2_AUTH_URL=http://auth:9100"
    ports:
      - "8080:80"
    depends_on:
      - "api"

  rabbitmq:
    image: rabbitmq:management
    environment:
      - "RABBITMQ_DEFAULT_USER=rmq-user"
      - "RABBITMQ_DEFAULT_PASS=rmq-pass"
    hostname: rabbitmq
    expose:
     - "5672"

  mongodb:
    image: tutum/mongodb
    environment:
      - "MONGODB_USER=stackstorm-user"
      - "MONGODB_PASS=stackstorm-pass"
      - "MONGODB_DATABASE=stackstorm-db"
    expose:
     - "27017"
